ingress:
  apiVersion: 'networking.k8s.io/v1'

  namespace: 'rewards-[JIRA_ID]'
  name: 'rewards-[JIRA_ID]-ingress'

  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: 'HTTP'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:me-central-1:420360167813:certificate/b5404ebb-c55c-4089-9b6e-bf854f31de14'
    alb.ingress.kubernetes.io/group.name: 'default'
    alb.ingress.kubernetes.io/healthcheck-path: '/health/'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/tags: 'Name=ygg-qa-default-alb-eks-tf, Platform=EKS, Environment=qa'
    alb.ingress.kubernetes.io/wafv2-acl-arn: 'arn:aws:wafv2:me-central-1:420360167813:regional/webacl/AWSRegionalWAF2/6de85d45-493c-463a-8878-fb0a41c8192c'
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/subnets: 'ygg-qa-public-me-central-1a, ygg-qa-public-me-central-1b, ygg-qa-public-me-central-1c'
    alb.ingress.kubernetes.io/load-balancer-attributes: 'idle_timeout.timeout_seconds=120'
    kubernetes.io/ingress.class: 'alb'

  rules:
    - host: 'rewards-[JIRA_ID].sit.yougotagift.co'
      http:
        paths:
          - backend:
              service:
                name: 'rewards-[JIRA_ID]-nginx'
                port:
                  number: 80
            path: '/*'
            pathType: 'ImplementationSpecific'
