namespace: 'rewards-[JIRA_ID]'

app_name: 'rewards-[JIRA_ID]'
environment: 'qa'

service:
  name: 'rewards-[JIRA_ID]-app'
  default:
    port: 8000
    protocol: 'TCP'
    targetPort: 8000

enableHPA: false
hpa:
  name: 'rewards-[JIRA_ID]-app-hpa'
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

enableKedaCron: true
keda:
  name: 'rewards-[JIRA_ID]-app-keda'
  minReplicas: 0
  desiredReplicas: 2
  maxReplicas: 2
  start: "0 7 * * 1-5"
  end: "0 22 * * 1-5"
  cpu: 80

pdb:
  name: 'rewards-[JIRA_ID]-app-pdb'
  minAvailable: 1

deployment:
  name: 'rewards-[JIRA_ID]-app-deployment'
  replicas: 2
  maxSurge: 100%
  maxUnavailable: 50%
  serviceAccountName: 'ygag-rewards-vault'

  containers:
    default:
      name: 'app'
      imagePullPolicy: 'Always'
      image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/ygg/rewards/backend-app:[BUILD_TAG]'
      command: '["/ygag/deployment/app/entrypoint.sh"]'
      args: '["app", "register-checkout"]'
      env:
        - name: 'DJANGO_SETTINGS_MODUL'
          value: 'DJANGO_SETTINGS_MODULE'
      port: 8000
      memory:
        requests: 590Mi
        limits: 767Mi
      cpu:
        requests: 165m
      health:
        path: '/health/'
        port: 8000
        scheme: 'HTTP'
      startupProbe:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 7
      readinessProbe:
        initialDelaySeconds: 0
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      livenessProbe:
        initialDelaySeconds: 0
        periodSeconds: 15
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      volumeMounts:
        - mountPath: '/ygag/logs/'
          name: 'ygag-rewards-[JIRA_ID]-qa-app-logs'
        - name: 'rewards-app-env-volume'
          mountPath: "/vault/secrets"
        - name: rewards-certs-msk-volume
          mountPath: "/ygag/certs/msk"

  volumes:
    - name: 'ygag-rewards-[JIRA_ID]-qa-app-logs'
      hostPath:
        path: '/home/ec2-user/ygag-logs/ygag-rewards-[JIRA_ID]-qa/app'
    - name: rewards-app-env-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "rewards-envs"
    - name: rewards-certs-msk-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "rewards-certs-msk"

  initContainers:
    database:
      - image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/postgres:13.11'
        cmd: 'pg_isready -p 5432'
        host: 'rewards-[JIRA_ID]-database'
        name: 'init-database'
    redis:
      - image: '420360167813.dkr.ecr.me-central-1.amazonaws.com/qa/redis:6.2.4'
        host: 'rewards-[JIRA_ID]-redis'
        name: 'init-redis'

  nodeSelector:
    key: 'karpenter.sh/nodepool'
    value: 'default'

  topologySpreadConstraints:
    - maxSkew: 2
      topologyKey: 'topology.kubernetes.io/zone'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'rewards-[JIRA_ID]'
          tier: app
    - maxSkew: 2
      topologyKey: 'kubernetes.io/hostname'
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: 'rewards-[JIRA_ID]'
          tier: app

  priorityClassName: 'qa-medium'
  terminationGracePeriodSeconds: 60

