SecretProviderClass:
- name: rewards-envs
  namespace: rewards-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-rewards-app-role"
    objects: |
      - objectName: "application.env"
        secretPath: "ygag-secrets/data/rewards/qa/rewards/env-uae"
        secretKey: "app-env"
      - objectName: "settings_local.py"
        secretPath: "ygag-secrets/data/rewards/qa/rewards/env-uae"
        secretKey: "settings_local.py"

- name: rewards-certs-msk
  namespace: rewards-[JIRA_ID]
  provider: vault
  parameters:
    roleName: "ygg-eks-v2-rewards-app-role"
    objects: |
      - objectName: "aws-truststore.cert"
        secretPath: "ygag-secrets/data/rewards/qa/rewards/certs-msk"
        secretKey: "aws-truststore.cert"
      - objectName: "ca-key.pem"
        secretPath: "ygag-secrets/data/rewards/qa/rewards/certs-msk"
        secretKey: "ca-key.pem"
      - objectName: "ca-cert.cert"
        secretPath: "ygag-secrets/data/rewards/qa/rewards/certs-msk"
        secretKey: "ca-cert.cert"