# This is a basic workflow to help you get started with Actions

name: testing work flow file

# Controls when the workflow will run
on:
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : before checkout
        run: |
          echo "executing pwd"
          pwd
          echo "excuting ls"
          ls
          
          cd ../../
          tree
        
    

    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name : after checkout
        run : |
          echo "excuting pwd"
          pwd
          echo "excuting ls"
          ls
          tree
